version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - web_network
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    networks:
      - web_network
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 7000:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=db_wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    networks:
      - web_network
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 5000:80

networks:
  web_network:
    name: wlamp
    driver: bridge        